### ISSUE TITLE
Should `xmlns="http://www.w3.org/2005/Atom"` be emitted on the `<feed>` element?

### ISSUE THREAD

**Issue by phaylon** [rust-syndication/atom#1]
Currently it's possible to set namespaces, but not the default namespace, which also isn't emitted on the `<feed>` element.

It seems like a lack of the default namespace attribute gives Firefox trouble when detecting Atom feeds.

**Comment by jameshurst** [comment]
Thanks for pointing this out!

**Comment by bsean95531** [comment]
You commented on stolen file
