### ISSUE TITLE
Replace String with ::chrono::DateTime<::chrono::FixedOffset>

### ISSUE THREAD

**Issue by DCjanus** [rust-syndication/atom#10]
It seems there are no typed date or time in this crate, for example, `Feed#updated`, `Entry#updated` and `Entry#published`.

Should we replace `String` with `::chrono::DateTime<::chrono::FixedOffset>`? with typed field, there will be less confusion.

I'm going to do this, I think this crate is excellent, It is my honor to participate in this project.

I'm not native speaker, I believe that there are many errors in my narrative, please forgive me.

**Comment by whtsky** [comment]
@DCjanus 's proposal is always helpful to me.
