### ISSUE TITLE
Regression in last version

### ISSUE THREAD

**Issue by andy128k** [rust-syndication/atom#20]
The crate stopped to parse feeds with non-conformant date fields. 
[Example feed](http://www.arewewebyet.org/atom.xml)

There was a possibility to loosely parse date fields with custom code (or just skip them). But now the whole feed is discarded with error `WrongDatetime`.

**Comment by bheisler** [comment]
I've run into this as well, although in my case it's simply a matter of whitespace around the date string. For this particular feed, trimming whitespace before calling `parse_from_rfc3339` would be sufficient.

[Example feed](http://www.volpinprops.com/feed/atom/)

**Comment by andy128k** [comment]
Any updates here? Two versions were already released (0.7.0 and 0.8.0) with broken behavior, while this issue was not addressed.

There is no workaround for this issue (whole feed is rejected).
