### ISSUE TITLE
Add `*_mut` getters

### ISSUE THREAD

**Issue by tesaguri** [rust-syndication/atom#24]
Fields of types like `Feed` have:

- Immutable getters (like `fn title(&self) -> &str`), and
- Setters (like `fn set_title(&mut self, title: ...)`)

They works fine most of the time, but when you want to get an owned `String` from a `Feed`, you have to clone a `&str` returned by the setter, rather than just taking the ownership out of the `Feed`.

If `Feed` had mutable getters like `fn title_mut(&mut self) -> &mut String`, you could take the field without cloning:

```rust
use std::mem;
use atom_syndication::Feed;

let mut feed = Feed::default();
feed.set_title("Feed Title");
let title = mem::take(feed.title_mut());
assert_eq!(title, "Feed Title");
assert_eq!(feed.title(), "");
```

If the idea seems fine to you, I'd love to make a pull request (to this repository and rust-syndication/rss).

**Comment by DCjanus** [comment]
in my opinion, maybe expose field directly is a better solution. And in Rust, because of borrow check, getter/setter might be a bad pattern.
