### ISSUE TITLE
Is this crate abandoned?

### ISSUE THREAD

**Issue by andy128k** [rust-syndication/atom#26]
Issues and pull-requests are staying unaddressed for months. The same with rss crate.

**Comment by AnderEnder** [comment]
@frewsxcv, @chrisppy, @jameshurst, @DCjanus?

**Comment by frewsxcv** [comment]
not abandoned, just doesn't have a maintainer it seems. @andy128k @AnderEnder i just invited you both to the rust-syndication github org. feel free to merge your pull requests and publish a new version!

**Comment by andy128k** [comment]
@frewsxcv  Thanks! I will work on current issues and PRs.

I have moved new repo/create into this organization. I wanted to give a permissions to publish it to other members of org. But I could not.

It looks like I am not in a corresponding team ('publish'?). Can you add me (and @AnderEnder)  to the team?

**Comment by frewsxcv** [comment]
> It looks like I am not in a corresponding team ('publish'?). Can you add me (and @AnderEnder) to the team?

done!
