### ISSUE TITLE
Feeds starting with <?xml version="1.0" encoding="UTF-8"?>

### ISSUE THREAD

**Issue by bjorn3** [rust-syndication/atom#32]
For example https://headcrab.rs/feed.xml

**Comment by andy128k** [comment]
@bjorn3 Your link goes to RSS feed, not to Atom one. You should use [another crate](https://github.com/rust-syndication/rss).

**Comment by bjorn3** [comment]
Ah my bad. It seems that atom also allows `<?xml` though.

**Comment by sabitm** [comment]
Hi, when reading from this https://www.reddit.com/r/rust/.rss atom feed, the library returns `InvalidStartTag` error. Should I manually remove the `<?xml version="1.0" encoding="UTF-8"?>` tag?
