### ISSUE TITLE
Introduce and maintain a changelog

### ISSUE THREAD

**Issue by andy128k** [rust-syndication/atom#49]

**Comment by ayrat555** [comment]
Thank you for creating this issue

**Comment by Lonami** [comment]
Should this be closed now that https://github.com/rust-syndication/atom/commit/5f804bcf243db5f5ffc74121f0f3c906a93805cb introduced the `CHANGELOG.md` file?

**Comment by andy128k** [comment]
@Lonami you are right. This may be closed.
