### ISSUE TITLE
Implement Serde's Serialize/Deserialize traits (per C-SERDE guideline)

### ISSUE THREAD

**Issue by djc** [rust-syndication/atom#5]
I think this would make sense for stuff like `Feed`, `Entry`, and others. Would a PR for this be accepted?

**Comment by frewsxcv** [comment]
relevant discussion in https://github.com/rust-syndication/rss/issues/54

**Comment by djc** [comment]
So, I suppose a PR for this would now be accepted? 😄

**Comment by frewsxcv** [comment]
yep!
