### ISSUE TITLE
Should `content` be escaped?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [rust-syndication/atom#51]
Using HTML within a Content seems to include it verbatim in the output. This causes validation warnings at best, and broken XML at worst (e.g. `.value("</content>".to_owned())`).

I would expect the library to escape the content as text, unless I'm misunderstanding the Atom spec

**Comment by andy128k** [comment]
This is a tricky question. Atom allows to have a XHTML as a content. Unconditional escaping will break such scenario.

We could serialize content [the same way we serialize `Text`](https://github.com/rust-syndication/atom/blob/master/src/text.rs#L204-L208). Unfortunately it will be a breaking change (so, minor version bump is needed).

BTW, PRs are welcomed :smirk:

**Comment by vpzomtrrfrt** [comment]
Would such a change then be string matching on `content_type`?

**Comment by andy128k** [comment]
@vpzomtrrfrt Yes, it would be. Actually spec allows it to be [any MIME type](https://datatracker.ietf.org/doc/html/rfc4287#section-4.1.3) (not only XHTML). So, maybe it will be a bit more complex than `Text` (which is limited to only 3 types).
