### ISSUE TITLE
https://www.facebook.com/profile.php?id=100015363047007

### ISSUE THREAD

**Issue by yzwwn** [rust-syndication/atom#60]
لانه تم تغيير معلومات حسابي فيس بوك ولا استطيع الوصول الى بريد الالكتروني الجديد ولكن لدي رسائل البريد الالكتروني القديم الخاص بالحساب
https://www.facebook.com/profile.php?id=100015363047007
| مراجع

#56 #59 [لانه تم تغيير معلومات حسابي فيس بوك ولا استطيع الوصول الى بريد الالكتروني الجديد ولكن لدي رسائل البريد الالكتروني القديم الخاص بالحساب https://www.facebook.com/profile.php?id=100015363047007 | مراجع](https://www.facebook.com/profile.php?id=100015363047007)

**Comment by DCjanus** [comment]
Maybe we should block this account

**Comment by yzwwn** [comment]
اريد استعادته للوصول الى معلوماتي

ابو يزون

في الاثنين، ٢٠ ديسمبر ٢٠٢١ ٥:٣٤ ص DCjanus ***@***.***> كتب:

**Comment by yzwwn** [comment]
> ربما يجب علينا حظر هذا الحساب

😔

**Comment by yzwwn06** [comment]
قامو باختراق حسابي الفيس وتغيرت المعلومات https://www.facebook.com/profile.php?id=100015363047007

**Comment by yzwwn06** [comment]
![Screenshot_٢٠٢٢٠٥٠٣-١١٣٢٣٧_Gmail](https://user-images.githubusercontent.com/96582722/166426089-936a8f43-97bb-4c7f-ac8c-e364a69de1e5.jpg)
