### ISSUE TITLE
`Error` is not `Send` anymore in v0.12.5

### ISSUE THREAD

**Issue by anphir** [rust-syndication/atom#88]
The last update breaks use cases like polling and parsing multiple feeds in parallel using threads.

In v0.12.4 code like this would compile just fine:

```rust
let handle = std::thread::spawn(
    || -> Result<atom_syndication::Feed, atom_syndication::Error> {
        // Poll feed and parse it.
        todo!()
    },
 );
```
With v0.12.5 compilation fails:

```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
   --> poll/src/bin/test.rs:2:18
    |
2   |       let handle = std::thread::spawn(
    |  __________________^
3   | |         || -> Result<atom_syndication::Feed, atom_syndication::Error> {
4   | |             // Poll feed and parse it.
5   | |             todo!()
6   | |         },
7   | |     );
    | |_____^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
    |
    = help: the trait `Send` is not implemented for `(dyn std::error::Error + 'static)`, which is required by `Result<Feed, atom_syndication::Error>: Send`
    = note: required for `Unique<(dyn std::error::Error + 'static)>` to implement `Send`
```

The problem seems to be the change of `XmlError` from `pub struct XmlError(quick_xml::Error)` in v0.12.4 to `XmlError(Box<dyn StdError>)` in v0.12.5.
I don't know why that change was made, so can't suggest a fix for the described problem.

Many thanks for your work on this library.

**Comment by andy128k** [comment]
Oops. That's unfortunate.

The change in a definition of `XmlError` was made because of a change in a `quick_xml` crate. It does not have a single error type anymore, so a `Box<dyn StdError>` was used.
